server:
  port: 9090

spring:
  datasource:
    internal:
      url: jdbc:mysql://localhost:3306/adms_db?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: password
      driverClassName: com.mysql.cj.jdbc.Driver

    external:
      url: jdbc:mysql://localhost:3306/ibslhr?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: password
      driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
      #naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.jdbc.time_zone: Asia/Colombo
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: cbadev2021@gmail.com
    password: rqtxmosiovfndjpg
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: micro-aoer
    timeZone: Asia/Colombo

  jackson:
    time-zone: Asia/Colombo

logging:
  level:
    root: INFO
    com:
      cba:
        mpos:
          aoer: DEBUG

sender:
  mail:
    address: cbadev2021@gmail.com